# ----------------------------------------------- #
# Note: this file originates in template-node-js #
# ----------------------------------------------- #

ENABLE:
  - ACTION
  - BASH
  - MAKEFILE
  - REPOSITORY
  - TERRAFORM
  - HTML
  - ENV
  - JAVASCRIPT
  - JSX
  - EDITORCONFIG
  - JSON
  - DOCKERFILE
  - MARKDOWN
  - YAML
  - CSS
  - SQL

DISABLE_LINTERS:
  - REPOSITORY_TRIVY
  - SPELL_CSPELL
  - JSON_PRETTIER
  - YAML_PRETTIER
  - JAVASCRIPT_PRETTIER
  - REPOSITORY_DEVSKIM

LOG_LEVEL: INFO
CONFIG_REPORTER: false
FLAVOR_SUGGESTIONS: false
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
VALIDATE_ALL_CODEBASE: false
IGNORE_GENERATED_FILES: true
FILTER_REGEX_EXCLUDE: (dist/*|README.md|test/fixtures/*|vendor/*|/schemas/*)

MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdown-lint.yml
REPOSITORY_CHECKOV_CONFIG_FILE: .checkov.yml
YAML_YAMLLINT_CONFIG_FILE: .yamllint.yml
