# ---------------------------------------------------- #
# Note: this file originates in template-node-js #
# ---------------------------------------------------- #

name: push

on:
  - push
  - workflow_dispatch

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

permissions:
  contents: write
  statuses: write
  pull-requests: write

jobs:
  metadata:
    uses: ./.github/workflows/job-metadata.yml

  lint-commits:
    uses: ./.github/workflows/job-lint-commits.yml

  lint-content:
    uses: ./.github/workflows/job-lint-javascript.yml
    permissions:
      contents: write
      statuses: write
      pull-requests: write

  npm-audit:
    uses: ./.github/workflows/job-npm-audit.yml

  npm-test:
    uses: ./.github/workflows/job-npm-test.yml
    secrets: inherit
    with:
      name: npm-test

  release:
    needs:
      - metadata
      - lint-commits
      - lint-content
      - npm-audit
      - npm-test

    permissions:
      contents: write
      packages: write
      pull-requests: write

    if: ${{ needs.metadata.outputs.repository_default_branch == github.ref_name }}

    uses: ./.github/workflows/job-semantic-release.yml
    secrets: inherit
